# Generated by Django 3.1.4 on 2021-01-18 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_volunteer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charitiy_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charitylocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_appointment', to='userApp.category'),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charities_appointment', to='userApp.charity'),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charitiy_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
