# Generated by Django 3.1.4 on 2020-12-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0002_auto_20201228_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charitylocation',
            old_name='charity',
            new_name='user',
        ),
    ]
