# Generated by Django 3.1 on 2021-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0002_auto_20210118_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='size',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
