# Generated by Django 3.1.4 on 2020-12-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityApp', '0003_auto_20201228_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='creator',
            new_name='user',
        ),
    ]
