# Generated by Django 3.1.4 on 2020-12-28 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityApp', '0005_auto_20201228_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='charity',
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charitiy_news', to='userApp.user'),
            preserve_default=False,
        ),
    ]
