# Generated by Django 3.1.4 on 2020-12-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityApp', '0006_auto_20201228_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='charity_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='charitiy_activities', to='userApp.user'),
            preserve_default=False,
        ),
    ]
