# Generated by Django 3.1.4 on 2020-12-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20201228_2201'),
        ('charityApp', '0007_auto_20201228_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_appointment', to='userApp.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
